name: Build RayTraceAntiXray

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean package --batch-mode

      - name: Upload JAR
        uses: actions/upload-artifact@v6
        with:
          name: RayTraceAntiXray
          path: |
            RayTraceAntiXray/target/*.jar
            !RayTraceAntiXray/target/*-sources.jar
            !RayTraceAntiXray/target/*-javadoc.jar
