name: Build RayTraceAntiXray

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Paperweight/Libs derlemesi arka planda git commit/am kullandığından bu şarttır
      - name: Configure Git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"

      - name: Make scripts executable
        run: |
          chmod +x mvnw
          chmod +x compilew.sh 2>/dev/null || true

      - name: Build with Maven Wrapper
        run: ./mvnw clean package --batch-mode -e

      - name: Upload Built JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RayTraceAntiXray-jar
          path: RayTraceAntiXray/target/*.jar
          if-no-files-found: error
